### ISSUE TITLE
atp_matches 2020 columns

### ISSUE THREAD

**Issue by ibarrau** [JeffSackmann/tennis_atp#119]
Hi, first of all thanks for this incredible tennis data because is the best I have found in a long time on the internet.
The problem is that the 2020 csv of the atp_matches are like moved. When the losers data starts are in a wrong column. Losers_Name has numbers and the real name is under other column.

Hope you can find a solution for this! and again thanks for this great data.

**Comment by arnautienda** [comment]
Hello, 
This dataset is amazing as ibarrau set. Thank you for that.

I have the same problem. It starts in 2019, and it happens because of the winner and loser age, which have commas and it messes up the csv conversion. Example:

2019-M-DC-2019-QLS-M-SWE-COL-01,Davis Cup QLS R1: SWE vs COL,Clay,4,D,20190201,4,105292,,,Alejandro Gonzalez,R,,COL,**29.9712525667,337,72**,111200,,,Elias Ymer,R,,SWE,22.8008213552,116,485,6-3 6-3,3,RR,56,1,3,55,34,22,14,9,2,4,1,6,53,29,17,8,9,4,9.

I have also noticed that in this cases, the information is not complete, and there are not the same fields as for the other matches. 

Is there any way that we can obtain the complete info of those matches?
[matches_errors.xlsx](https://github.com/JeffSackmann/tennis_atp/files/4097013/matches_errors.xlsx)

Please find attached the matches that have this problem.
Thank you in advance.

**Comment by JeffSackmann** [comment]
header rows are fixed now
