### ISSUE TITLE
Request for information

### ISSUE THREAD

**Issue by CaptainMiddle** [JeffSackmann/tennis_atp#137]
Hello,

I am a French engineer and a huge tennis fan.
I am developing a fantasy tennis website based on tennis results.  I just discovered your incredible database and I was wondering if I could use it or if you could guide and help me to find the perfect APIs that suit my need.
We can discuss it on the phone or by email if you want further information.

Best,

Maxime

**Comment by JeffSackmann** [comment]
sorry for the late response. My datasets are almost definitely not what you're looking for, since they are updated at most once per week, and sometimes less often. This is a hobby project for me, so I make no guarantees.

If you want to use these datasets as part of some other project anyway, please consult the license information in the readme.
