### ISSUE TITLE
Questionable reliability of ATP data on handedness.

### ISSUE THREAD

**Issue by Mick1303** [JeffSackmann/tennis_atp#226]
It is not for the first time I notice that ATP has very limited data on certain player (no age, no height) but the handedness is stated as "right-handed". I have a suspicion that somewhere in their engine they assign it by default, without actually verifying.
I'm not sure about the solution, but lately I do not include the data on handedness from their site if DOB is missing. Especially for not so recent players. And even for the recent they sometimes contradict ITF. Example:
https://www.itftennis.com/en/players/oscar-gabriel-morales-barrera/800503411/esp/jt/s/
This player is lefty on ITF site,
https://www.atptour.com/en/players/oscar-gabriel-morales-barrera/m0pw/overview
but righty on ATP site.

If you're in contact with someone from ATP, could you ask them about them possibly putting "righty" by default? Did they do it or not?

**Comment by JeffSackmann** [comment]
Yeah, I think that this has happened sometimes. It's not all the time, because there are so many players not identified as righty or lefty on the ATP site. (I think; maybe this is not true anymore?) I will ask the person I know, but I doubt he will have answer for us.

FWIW, for almost all players from the last 10+ years, I take handedness from ITF, mostly because players almost always appear in an ITF event before an ATP event.
