### ISSUE TITLE
Rankings for 1999-03-22 have wrong points

### ISSUE THREAD

**Issue by mcekovic** [JeffSackmann/tennis_atp#59]
Rankings for 1999-03-22 have wrong points for ranking 1-1000
For example second Sampras has more points 2735 (should be 3447) then first Moya 2704 (should be 3484)

**Comment by mcekovic** [comment]
As well as for:
02-09-1996
23-12-1996
30-12-1996
20-01-1997
24-03-1997
02-06-1997
30-06-1997
23-03-1998
01-06-1998
29-06-1998
07-09-1998
21-12-1998
28-12-1998
25-01-1999
22-03-1999
31-05-1999
28-06-1999

**Comment by JeffSackmann** [comment]
19960701 points aren't 'wrong', just missing all points for players 1-1000, as is the case on the ATP site:
https://www.atptour.com/en/rankings/singles?rankDate=1996-07-01&rankRange=0-100

I believe 20000110 was also previously fixed, though there are a few new players for that date in the latest commit.

I've probably brought back a few of the duplicate player-weeks that led to the issues summarized in #109 , but since I'm aiming to take care of those separately in the coming days, I'll leave those for now.

Finally, some of the 'fixed' dates have null ranking points for many -- but not all! -- players. Unfortunately that is the state of the data published by ATP, e.g. Jordi Mas here:
https://www.atptour.com/en/rankings/singles?rankDate=1996-12-23&rankRange=401-500

I recognize that many of the missing points totals can be inferred from surrounding players and/or reconstructed from results, but at this stage, I'm aiming only to reflect 'official' rankings and ranking points.
